# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='applicant name', max_length=200)),
                ('type', models.CharField(help_text='looking for type of role', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='timestamp when entry created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='timestamp when entry updated')),
            ],
        ),
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(help_text='occupation/job type', max_length=200)),
                ('city', models.CharField(help_text='city', max_length=200)),
                ('heat', models.FloatField(help_text='normalised heat value')),
                ('longitude', models.FloatField(help_text='longitude of the city')),
                ('latitude', models.FloatField(help_text='latitude of the city')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='timestamp when entry created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='timestamp when entry updated')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='address of the house', max_length=200)),
                ('city', models.CharField(help_text='city of the house', max_length=200)),
                ('longitude', models.FloatField(help_text='longitude of the house', null=True)),
                ('latitude', models.FloatField(help_text='latitude of the house', null=True)),
                ('prize', models.IntegerField(help_text='prise of the house')),
                ('squaremeters', models.IntegerField(help_text='square meters the house', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='timestamp when entry created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='timestamp when entry updated')),
                ('ad_id', models.IntegerField(help_text='id of arbetsformedlinen add to be used for new api request')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='the name of the company', max_length=200)),
                ('type', models.CharField(help_text='job type', max_length=200)),
                ('city', models.CharField(help_text='city of the company', max_length=200)),
                ('longitude', models.FloatField(help_text='longitude of the house')),
                ('latitude', models.FloatField(help_text='latitude of the house')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='timestamp when entry created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='timestamp when entry updated')),
                ('ad_id', models.IntegerField(help_text='id of arbetsformedlinen add to be used for new api request')),
            ],
        ),
    ]
